server.port: 7002
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db
  auto-index-creation: true

logging:
  level:
    root: INFO
    io.github.ddojai.channel: DEBUG

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080
